### ISSUE TITLE
Issue with vcsrepo

### ISSUE THREAD

**Issue by wingZero21** [icclab/vagrant-devstack#7]
Noticed that when downloading the vcs repo module does not seem to exist in the modules directory.

Would be worth adding this to the readme or adding it into the modules directory from the source (https://github.com/puppetlabs/puppetlabs-vcsrepo)

Error that occurs:
Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type vcsrepo at /tmp/vagrant-puppet/manifests/site.pp:43

Cheers
wingZero

**Comment by dizz** [comment]
Hey @wingZero21 - the module is already present as a git submodule (see: https://github.com/dizz/vagrant-devstack/blob/master/.gitmodules)
